---
url: https://www.googleapis.com/youtube/v3
type: activities
params:
  - key: part
    value:
      - 'contentDetails'
      - 'id'
      - 'snippet'
  - key: maxResults
    value:
      - '15'
  - key: channelId
    value:
      - 'UC2LZSB4R7Gzlhnql7lkQkRg'
  - key: key
    value:
      - 'AIzaSyAtbG3P1hZdGmvK8YzqIIIfCAcVKCXAJWo'
